=== open-mpi/hwloc/hwloc/hwloc2.dtd
<!--
  SPDX-License-Identifier: BSD-3-Clause
  Copyright © 2009      CNRS
  Copyright © 2009-2026 Inria.  All rights reserved.
  Copyright © 2009-2011 Université Bordeaux.
  See COPYING in top-level directory.

  This is the DTD for hwloc v2.x XMLs.
 -->

<!ELEMENT topology (object+,distances2*,distances2hetero*,support*,memattr*,cpukind*,info*,memtier*,pci_locality*)>
<!ATTLIST topology version CDATA "">

<!ELEMENT object (page_type*,info*,userdata*,object*)>
<!ATTLIST object type (Machine | Misc | Group | NUMANode | MemCache | Package | Die | L1Cache | L2Cache | L3Cache | L4Cache | L5Cache | L1iCache | L2iCache | L3iCache | Core | PU | Bridge | PCIDev | OSDev) #REQUIRED>
<!ATTLIST object subtype CDATA "" >
<!ATTLIST object os_index CDATA "-1" >
<!ATTLIST object id CDATA "-1" >
<!ATTLIST object gp_index CDATA "-1" >
<!ATTLIST object hw_id CDATA "0" >
<!ATTLIST object name CDATA "" >
<!ATTLIST object local_memory CDATA "0" >
<!ATTLIST object cache_size CDATA "0" >
<!ATTLIST object cache_linesize CDATA "0" >
<!ATTLIST object cache_associativity CDATA "0" >
<!ATTLIST object cache_type CDATA "0" >
<!ATTLIST object cache_inclusive CDATA "0" >
<!ATTLIST object cpuset CDATA "0" >
<!ATTLIST object complete_cpuset CDATA "" >
<!ATTLIST object allowed_cpuset CDATA "" >
<!ATTLIST object nodeset CDATA "" >
<!ATTLIST object complete_nodeset CDATA "" >
<!ATTLIST object allowed_nodeset CDATA "" >
<!ATTLIST object depth CDATA "-1" >
<!ATTLIST object kind CDATA "0" >
<!ATTLIST object subkind CDATA "0" >
<!ATTLIST object dont_merge CDATA "0" >
<!ATTLIST object bridge_type CDATA "" >
<!ATTLIST object bridge_pci CDATA "" >
<!ATTLIST object pci_busid CDATA "" >
<!ATTLIST object pci_type CDATA "" >
<!ATTLIST object pci_link_speed CDATA "0." >
<!ATTLIST object osdev_type CDATA "" >

<!ELEMENT info EMPTY>
<!ATTLIST info name CDATA #REQUIRED>
<!ATTLIST info value CDATA #REQUIRED>

<!ELEMENT distances2 (indexes+,u64values+)>
<!ATTLIST distances2 type CDATA #REQUIRED>
<!ATTLIST distances2 nbobjs CDATA #REQUIRED>
<!ATTLIST distances2 indexing CDATA #REQUIRED>
<!ATTLIST distances2 kind CDATA #REQUIRED>
<!ATTLIST distances2 name CDATA "">

<!ELEMENT distances2hetero (indexes+,u64values+)>
<!ATTLIST distances2hetero nbobjs CDATA #REQUIRED>
<!ATTLIST distances2hetero kind CDATA #REQUIRED>
<!ATTLIST distances2hetero name CDATA "">

<!ELEMENT memattr (memattr_value*)>
<!ATTLIST memattr name CDATA #REQUIRED>
<!ATTLIST memattr flags CDATA #REQUIRED>

<!ELEMENT memattr_value EMPTY>
<!ATTLIST memattr_value target_obj_gp_index CDATA "">
<!ATTLIST memattr_value target_obj_type CDATA #REQUIRED>
<!ATTLIST memattr_value value CDATA #REQUIRED>
<!ATTLIST memattr_value initiator_cpuset CDATA "">
<!ATTLIST memattr_value initiator_obj_gp_index CDATA "">
<!ATTLIST memattr_value initiator_obj_type CDATA "">

<!ELEMENT indexes (#PCDATA)>
<!ATTLIST indexes length CDATA #REQUIRED>

<!ELEMENT u64values (#PCDATA)>
<!ATTLIST u64values length CDATA #REQUIRED>

<!ELEMENT userdata (#PCDATA)>
<!ATTLIST userdata name CDATA "" >
<!ATTLIST userdata length CDATA "0" >
<!ATTLIST userdata encoding CDATA "" >

<!ELEMENT support EMPTY>
<!ATTLIST support name CDATA #REQUIRED>
<!ATTLIST support value CDATA "1" >

<!ELEMENT cpukind (info*)>
<!ATTLIST cpukind cpuset CDATA "0">
<!ATTLIST cpukind forced_efficiency CDATA "-1">

<!ELEMENT memtier (info*)>
<!ATTLIST memtier kinds CDATA "0">
<!ATTLIST memtier nodeset CDATA "0">

<!ELEMENT pci_locality EMPTY>
<!ATTLIST pci_locality domain CDATA #REQUIRED>
<!ATTLIST pci_locality bus_min CDATA #REQUIRED>
<!ATTLIST pci_locality bus_max CDATA #REQUIRED>
<!ATTLIST pci_locality cpuset CDATA #REQUIRED>

<!-- ignored since 3.0 -->
<!ELEMENT page_type EMPTY>
<!ATTLIST page_type size CDATA #REQUIRED>
<!ATTLIST page_type count CDATA #REQUIRED>

=== open-mpi/hwloc/tests/hwloc/xml/2intel64-1n2c-numaroot.v1tov2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" cpuset="0x00000003" complete_cpuset="0x00000003" allowed_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" allowed_nodeset="0x00000001" gp_index="2">
    <info name="hwlocVersion" value="v1.11-20170902.0906.git16cb39b"/>
    <info name="ProcessName" value="lstopo-no-graphics"/>
    <object type="NUMANode" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="1" local_memory="2147074048">
      <page_type size="4096" count="0"/>
      <info name="hwlocVersion" value="v1.11-20170902.0906.git16cb39b"/>
      <info name="ProcessName" value="lstopo-no-graphics"/>
    </object>
    <object type="Package" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="3">
      <info name="CPUModel" value="QEMU Virtual CPU version (cpu64-rhel6)"/>
      <info name="CPUVendor" value="GenuineIntel"/>
      <info name="CPUFamilyNumber" value="6"/>
      <info name="CPUModelNumber" value="13"/>
      <info name="CPUStepping" value="3"/>
      <object type="L2Cache" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="4" cache_size="4194304" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
        <info name="Inclusive" value="0"/>
        <object type="L1Cache" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="5" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
          <info name="Inclusive" value="0"/>
          <object type="L1iCache" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="6" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
            <info name="Inclusive" value="0"/>
            <object type="Core" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="7">
              <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="8"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Package" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="9">
      <info name="CPUModel" value="QEMU Virtual CPU version (cpu64-rhel6)"/>
      <info name="CPUVendor" value="GenuineIntel"/>
      <info name="CPUFamilyNumber" value="6"/>
      <info name="CPUModelNumber" value="13"/>
      <info name="CPUStepping" value="3"/>
      <object type="L2Cache" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="10" cache_size="4194304" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
        <info name="Inclusive" value="0"/>
        <object type="L1Cache" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="11" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
          <info name="Inclusive" value="0"/>
          <object type="L1iCache" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="12" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
            <info name="Inclusive" value="0"/>
            <object type="Core" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="13">
              <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="14"/>
            </object>
          </object>
        </object>
      </object>
    </object>
  </object>
  <support name="discovery.pu"/>
  <support name="discovery.numa"/>
  <support name="discovery.numa_memory"/>
  <support name="discovery.disallowed_pu"/>
  <support name="discovery.disallowed_numa"/>
  <support name="custom.exported_support"/>
</topology>

=== open-mpi/hwloc/doc/images/ppc64-with-smt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0xf0f0f0f0" complete_cpuset="0xf0f0f0f0" allowed_cpuset="0xf0f0f0f0" nodeset="0x00000003" complete_nodeset="0x00000003" allowed_nodeset="0x00000003" gp_index="1">
    <object type="Group" cpuset="0x0000f0f0" complete_cpuset="0x0000f0f0" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="74" kind="1001" subkind="0">
      <object type="NUMANode" os_index="0" cpuset="0x0000f0f0" complete_cpuset="0x0000f0f0" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2" local_memory="31943819264">
        <page_type size="65536" count="487424"/>
        <page_type size="16777216" count="0"/>
      </object>
      <object type="PU" os_index="4" cpuset="0x00000010" complete_cpuset="0x00000010" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="8"/>
      <object type="PU" os_index="5" cpuset="0x00000020" complete_cpuset="0x00000020" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="9"/>
      <object type="PU" os_index="6" cpuset="0x00000040" complete_cpuset="0x00000040" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="10"/>
      <object type="PU" os_index="7" cpuset="0x00000080" complete_cpuset="0x00000080" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="11"/>
      <object type="PU" os_index="12" cpuset="0x00001000" complete_cpuset="0x00001000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="16"/>
      <object type="PU" os_index="13" cpuset="0x00002000" complete_cpuset="0x00002000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="17"/>
      <object type="PU" os_index="14" cpuset="0x00004000" complete_cpuset="0x00004000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="18"/>
      <object type="PU" os_index="15" cpuset="0x00008000" complete_cpuset="0x00008000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="19"/>
    </object>
    <object type="Group" cpuset="0xf0f00000" complete_cpuset="0xf0f00000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="75" kind="1001" subkind="0">
      <object type="NUMANode" os_index="1" cpuset="0xf0f00000" complete_cpuset="0xf0f00000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="20" local_memory="33554432000">
        <page_type size="65536" count="512000"/>
        <page_type size="16777216" count="0"/>
      </object>
      <object type="PU" os_index="20" cpuset="0x00100000" complete_cpuset="0x00100000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="26"/>
      <object type="PU" os_index="21" cpuset="0x00200000" complete_cpuset="0x00200000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="27"/>
      <object type="PU" os_index="22" cpuset="0x00400000" complete_cpuset="0x00400000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="28"/>
      <object type="PU" os_index="23" cpuset="0x00800000" complete_cpuset="0x00800000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="29"/>
      <object type="PU" os_index="28" cpuset="0x10000000" complete_cpuset="0x10000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="34"/>
      <object type="PU" os_index="29" cpuset="0x20000000" complete_cpuset="0x20000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="35"/>
      <object type="PU" os_index="30" cpuset="0x40000000" complete_cpuset="0x40000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="36"/>
      <object type="PU" os_index="31" cpuset="0x80000000" complete_cpuset="0x80000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="37"/>
    </object>
  </object>
</topology>

=== open-mpi/hwloc/tests/hwloc/xml/8ia64-2n2s2c+1n.v1tov2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0x000f000f" complete_cpuset="0x00ff00ff" allowed_cpuset="0x000f000f" nodeset="0x00010005" complete_nodeset="0x00010005" allowed_nodeset="0x00010005" gp_index="1">
    <info name="Backend" value="Linux"/>
    <info name="Architecture" value="ia64"/>
    <info name="hwlocVersion" value="1.11.8"/>
    <info name="ProcessName" value="lstopo"/>
    <object type="Group" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="28" kind="1001" subkind="0">
      <object type="NUMANode" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2" local_memory="102458458112"/>
      <object type="Package" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="4">
        <info name="CPUVendor" value="GenuineIntel"/>
        <info name="CPUFamilyNumber" value="32"/>
        <info name="CPUModelNumber" value="1"/>
        <info name="CPUModel" value="Dual-Core Intel(R) Itanium(R) Processor 9140N"/>
        <object type="Core" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="5">
          <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="6"/>
        </object>
        <object type="Core" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="7">
          <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="8"/>
        </object>
      </object>
      <object type="Package" os_index="1" cpuset="0x0000000c" complete_cpuset="0x0000000c" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="9">
        <info name="CPUVendor" value="GenuineIntel"/>
        <info name="CPUFamilyNumber" value="32"/>
        <info name="CPUModelNumber" value="1"/>
        <info name="CPUModel" value="Dual-Core Intel(R) Itanium(R) Processor 9140N"/>
        <object type="Core" os_index="0" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="10">
          <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="11"/>
        </object>
        <object type="Core" os_index="1" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="12">
          <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="13"/>
        </object>
      </object>
    </object>
    <object type="Group" cpuset="0x000f0000" complete_cpuset="0x000f0000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="29" kind="1001" subkind="0">
      <object type="NUMANode" os_index="2" cpuset="0x000f0000" complete_cpuset="0x000f0000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="14" local_memory="103012106240"/>
      <object type="Package" os_index="131072" cpuset="0x00030000" complete_cpuset="0x00030000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="16">
        <info name="CPUVendor" value="GenuineIntel"/>
        <info name="CPUFamilyNumber" value="32"/>
        <info name="CPUModelNumber" value="1"/>
        <info name="CPUModel" value="Dual-Core Intel(R) Itanium(R) Processor 9140N"/>
        <object type="Core" os_index="0" cpuset="0x00010000" complete_cpuset="0x00010000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="17">
          <object type="PU" os_index="16" cpuset="0x00010000" complete_cpuset="0x00010000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="18"/>
        </object>
        <object type="Core" os_index="1" cpuset="0x00020000" complete_cpuset="0x00020000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="19">
          <object type="PU" os_index="17" cpuset="0x00020000" complete_cpuset="0x00020000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="20"/>
        </object>
      </object>
      <object type="Package" os_index="131073" cpuset="0x000c0000" complete_cpuset="0x000c0000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="21">
        <info name="CPUVendor" value="GenuineIntel"/>
        <info name="CPUFamilyNumber" value="32"/>
        <info name="CPUModelNumber" value="1"/>
        <info name="CPUModel" value="Dual-Core Intel(R) Itanium(R) Processor 9140N"/>
        <object type="Core" os_index="0" cpuset="0x00040000" complete_cpuset="0x00040000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="22">
          <object type="PU" os_index="18" cpuset="0x00040000" complete_cpuset="0x00040000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="23"/>
        </object>
        <object type="Core" os_index="1" cpuset="0x00080000" complete_cpuset="0x00080000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="24">
          <object type="PU" os_index="19" cpuset="0x00080000" complete_cpuset="0x00080000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="25"/>
        </object>
      </object>
    </object>
    <object type="Group" cpuset="0x0" complete_cpuset="0x0" nodeset="0x00010000" complete_nodeset="0x00010000" gp_index="30" kind="1001" subkind="0">
      <object type="NUMANode" os_index="16" cpuset="0x0" complete_cpuset="0x0" nodeset="0x00010000" complete_nodeset="0x00010000" gp_index="26" local_memory="1044660224"/>
    </object>
  </object>
  <distances2 type="NUMANode" nbobjs="3" kind="5" indexing="os">
    <indexes length="7">0 2 16 </indexes>
    <u64values length="27">10 17 17 17 17 10 14 14 14 </u64values>
  </distances2>
  <support name="discovery.pu"/>
  <support name="discovery.numa"/>
  <support name="discovery.numa_memory"/>
  <support name="discovery.disallowed_pu"/>
  <support name="discovery.disallowed_numa"/>
  <support name="custom.exported_support"/>
</topology>

=== open-mpi/hwloc/tests/hwloc/x86/AMD-K8-SledgeHammer-2xOpteron-250.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="3.0">
  <object type="Machine" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" allowed_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" allowed_nodeset="0x00000001">
    <object type="NUMANode" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001"/>
    <object type="Package" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001">
      <info name="CPUVendor" value="AuthenticAMD"/>
      <info name="CPUFamilyNumber" value="15"/>
      <info name="CPUModelNumber" value="5"/>
      <info name="CPUModel" value="AMD Opteron(tm) Processor 250"/>
      <info name="CPUStepping" value="10"/>
      <object type="L2Cache" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="1048576" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
        <object type="L1Cache" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="65536" depth="1" cache_linesize="64" cache_associativity="2" cache_type="1">
          <object type="L1iCache" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="65536" depth="1" cache_linesize="64" cache_associativity="2" cache_type="2">
            <object type="Core" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001">
              <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" hw_id="0"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Package" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001">
      <info name="CPUVendor" value="AuthenticAMD"/>
      <info name="CPUFamilyNumber" value="15"/>
      <info name="CPUModelNumber" value="5"/>
      <info name="CPUModel" value="AMD Opteron(tm) Processor 250"/>
      <info name="CPUStepping" value="10"/>
      <object type="L2Cache" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="1048576" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
        <object type="L1Cache" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="65536" depth="1" cache_linesize="64" cache_associativity="2" cache_type="1">
          <object type="L1iCache" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="65536" depth="1" cache_linesize="64" cache_associativity="2" cache_type="2">
            <object type="Core" os_index="0" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001">
              <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" hw_id="1"/>
            </object>
          </object>
        </object>
      </object>
    </object>
  </object>
  <info name="Backend" value="x86"/>
</topology>

=== open-mpi/hwloc/tests/hwloc/linux/allowed/test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="3.0">
  <object type="Machine" os_index="0" cpuset="0x0000747e" complete_cpuset="0x0000ffff" allowed_cpuset="0x0000747e" nodeset="0x00000006" complete_nodeset="0x0000000f" allowed_nodeset="0x00000006">
    <object type="Group" cpuset="0x0000000e" complete_cpuset="0x0000000f" nodeset="0x0" complete_nodeset="0x00000001" kind="1001" subkind="0">
      <object type="Core" os_index="0" cpuset="0x00000002" complete_cpuset="0x00000003" nodeset="0x0" complete_nodeset="0x00000001">
        <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x0" complete_nodeset="0x00000001"/>
      </object>
      <object type="Core" os_index="1" cpuset="0x0000000c" complete_cpuset="0x0000000c" nodeset="0x0" complete_nodeset="0x00000001">
        <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x0" complete_nodeset="0x00000001"/>
        <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x0" complete_nodeset="0x00000001"/>
      </object>
    </object>
    <object type="Group" cpuset="0x00000070" complete_cpuset="0x000000f0" nodeset="0x00000002" complete_nodeset="0x00000002" kind="1001" subkind="0">
      <object type="NUMANode" os_index="1" cpuset="0x00000070" complete_cpuset="0x000000f0" nodeset="0x00000002" complete_nodeset="0x00000002" local_memory="1073741824">
        <page_type size="4096" count="262144"/>
      </object>
      <object type="Core" os_index="2" cpuset="0x00000030" complete_cpuset="0x00000030" nodeset="0x00000002" complete_nodeset="0x00000002">
        <object type="PU" os_index="4" cpuset="0x00000010" complete_cpuset="0x00000010" nodeset="0x00000002" complete_nodeset="0x00000002"/>
        <object type="PU" os_index="5" cpuset="0x00000020" complete_cpuset="0x00000020" nodeset="0x00000002" complete_nodeset="0x00000002"/>
      </object>
      <object type="Core" os_index="3" cpuset="0x00000040" complete_cpuset="0x000000c0" nodeset="0x00000002" complete_nodeset="0x00000002">
        <object type="PU" os_index="6" cpuset="0x00000040" complete_cpuset="0x00000040" nodeset="0x00000002" complete_nodeset="0x00000002"/>
      </object>
    </object>
    <object type="Group" cpuset="0x00000400" complete_cpuset="0x00000f00" nodeset="0x00000004" complete_nodeset="0x00000004" kind="1001" subkind="0">
      <object type="NUMANode" os_index="2" cpuset="0x00000400" complete_cpuset="0x00000f00" nodeset="0x00000004" complete_nodeset="0x00000004" local_memory="1073741824">
        <page_type size="4096" count="262144"/>
      </object>
      <object type="Core" os_index="5" cpuset="0x00000400" complete_cpuset="0x00000c00" nodeset="0x00000004" complete_nodeset="0x00000004">
        <object type="PU" os_index="10" cpuset="0x00000400" complete_cpuset="0x00000400" nodeset="0x00000004" complete_nodeset="0x00000004"/>
      </object>
    </object>
    <object type="Group" cpuset="0x00007000" complete_cpuset="0x0000f000" nodeset="0x0" complete_nodeset="0x00000008" kind="1001" subkind="0">
      <object type="Core" os_index="6" cpuset="0x00003000" complete_cpuset="0x00003000" nodeset="0x0" complete_nodeset="0x00000008">
        <object type="PU" os_index="12" cpuset="0x00001000" complete_cpuset="0x00001000" nodeset="0x0" complete_nodeset="0x00000008"/>
        <object type="PU" os_index="13" cpuset="0x00002000" complete_cpuset="0x00002000" nodeset="0x0" complete_nodeset="0x00000008"/>
      </object>
      <object type="Core" os_index="7" cpuset="0x00004000" complete_cpuset="0x0000c000" nodeset="0x0" complete_nodeset="0x00000008">
        <object type="PU" os_index="14" cpuset="0x00004000" complete_cpuset="0x00004000" nodeset="0x0" complete_nodeset="0x00000008"/>
      </object>
    </object>
  </object>
  <info name="Backend" value="Synthetic"/>
  <info name="SyntheticDescription" value="numa:4 core:2 pu:2"/>
  <info name="LinuxCgroup" value="/dummy"/>
</topology>
